global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    dokku: PROM_LABEL

rule_files:
  - alert.rules

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'localhost:9090'
  - job_name: cadvisor
    scrape_interval: 5s
    scheme: https
    basic_auth:
      username: admin
      password: SUPER_STRONG_PW
    static_configs:
      - targets:
          - 'cadvisor.domain.com'

    metric_relabel_configs:
      - action: replace
        source_labels: [id]
        regex: '^/system\.slice/(.+)\.service$'
        target_label: systemd_service_name
        replacement: '${1}'